
name: Build
on:
  workflow_dispatch:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KO_DOCKER_REPO: docker.io/direktiv
    steps:
        - uses: olegtarasov/get-tag@v2.1
          id: tagName
          name: tagname
        - uses: actions/checkout@v2
          name: checkout
        - name: golang
          uses: actions/setup-go@v2
          with:
            go-version: 1.17
        - name: dockerhub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: ko
          run: |
            curl -L https://github.com/google/ko/releases/download/v0.9.3/ko_0.9.3_Linux_x86_64.tar.gz | tar xzf - ko
            chmod +x ./ko
            sudo mv ko /usr/local/bin
            ko version
        - name: publish
          run: |
            echo "tagname: $GIT_TAG_NAME"
            ko publish ./cmd/direktiv-source/ -B -t $GIT_TAG_NAME
            ko publish ./cmd/direktiv-source/ -B
            ko publish ./cmd/snmp-source/ -B -t $GIT_TAG_NAME
            ko publish ./cmd/snmp-source/ -B
