
name: Build
on:
  workflow_dispatch:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KO_DOCKER_REPO: docker.io/vorteil
    steps:
        - uses: actions/checkout@v2
          name: checkout
        - name: golang
          uses: actions/setup-go@v2
          with:
            go-version: 1.17
        - name: dockerhub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: ko
          run: |
            curl -L https://github.com/google/ko/releases/download/v0.9.3/ko_0.9.3_Linux_x86_64.tar.gz | tar xzf - ko
            chmod +x ./ko
            sudo mv ko /usr/local/bin
            ko version
        - name: publish
          run: |
            echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            export RV=${{env.RELEASE_VERSION}}
            if [ "$RV" == "main" ] || [ "$RV" == "" ] ; then export RV=latest; fi
            echo "RV set to $RV"
            ko publish ./cmd/direktiv-knative-source/ -B -t $RV
